# Generated by Django 5.2.7 on 2025-11-03 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactquery_bulkorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery')], default='card', max_length=20)),
                ('preferred_card_id', models.IntegerField(blank=True, help_text='ID of the preferred saved card', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Preference',
                'verbose_name_plural': 'Payment Preferences',
                'db_table': 'payment_preferences',
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card')], default='credit', max_length=10)),
                ('card_number_last4', models.CharField(help_text='Last 4 digits of card', max_length=4)),
                ('card_holder_name', models.CharField(blank=True, default='', max_length=100)),
                ('card_network', models.CharField(blank=True, help_text='e.g., Visa, Mastercard, Rupay', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('nickname', models.CharField(blank=True, help_text="User's nickname for the card", max_length=100)),
                ('razorpay_token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Card',
                'verbose_name_plural': 'Saved Cards',
                'db_table': 'saved_cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
