# Generated by Django 5.2.7 on 2025-11-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentpreference_savedcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcard',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentPreference',
        ),
        migrations.DeleteModel(
            name='SavedCard',
        ),
    ]
