# Generated by Django 5.2.7 on 2025-11-03 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_savedcard_user_delete_paymentpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery')], default='card', help_text='Preferred payment method type', max_length=20)),
                ('preferred_card_token_id', models.CharField(blank=True, help_text='Razorpay token ID for preferred saved card (if method is card)', max_length=100, null=True)),
                ('preferred_address_id', models.IntegerField(blank=True, help_text='ID of preferred shipping address', null=True)),
                ('payment_nickname', models.CharField(blank=True, help_text='User-defined nickname for payment method', max_length=100)),
                ('razorpay_customer_id', models.CharField(blank=True, help_text='Razorpay customer ID for saved cards', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Preference',
                'verbose_name_plural': 'Payment Preferences',
                'db_table': 'payment_preferences',
            },
        ),
    ]
