# Generated by Django 5.2.7 on 2025-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_paymentpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpreference',
            name='payment_nickname',
            field=models.CharField(blank=True, help_text='User nickname for this payment preference', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentpreference',
            name='preferred_address_id',
            field=models.IntegerField(blank=True, help_text='Preferred shipping address ID', null=True),
        ),
        migrations.AlterField(
            model_name='paymentpreference',
            name='preferred_card_token_id',
            field=models.CharField(blank=True, help_text='Razorpay token ID - card details stored only in Razorpay', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpreference',
            name='preferred_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentpreference',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, help_text='Razorpay customer ID for fetching saved cards', max_length=100, null=True),
        ),
    ]
