# Generated by Django 5.2.7 on 2025-11-03 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_paymentpreference_payment_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(help_text='Razorpay token ID', max_length=100, unique=True)),
                ('customer_id', models.CharField(help_text='Razorpay customer ID', max_length=100)),
                ('card_last4', models.CharField(help_text='Last 4 digits of card', max_length=4)),
                ('card_network', models.CharField(blank=True, help_text='Card network (Visa, Mastercard, etc.)', max_length=20)),
                ('card_type', models.CharField(blank=True, help_text='Card type (credit, debit)', max_length=20)),
                ('card_issuer', models.CharField(blank=True, help_text='Card issuer bank name', max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='User nickname for this card', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default card?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Card',
                'verbose_name_plural': 'Saved Cards',
                'db_table': 'saved_cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
