# Generated by Django 5.2.7 on 2025-11-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_savedcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpreference',
            name='payment_nickname',
        ),
        migrations.RemoveField(
            model_name='paymentpreference',
            name='preferred_address_id',
        ),
    ]
