# Generated by Django 5.2.7 on 2025-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_paymentpreference_payment_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, help_text='Razorpay customer ID - created once based on login user email, name, and phone', max_length=100, null=True),
        ),
    ]
