# Generated by Django 5.2.7 on 2025-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_migrate_razorpay_customer_id_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, help_text='Razorpay customer ID - created automatically on FIRST PAYMENT ATTEMPT (not at login), using user email, name, and phone', max_length=100, null=True),
        ),
    ]
