# Generated by Django 5.2.7 on 2025-11-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_razorpay_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpreference',
            name='preferred_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('cod', 'Cash on Delivery')], default='card', max_length=20),
        ),
    ]
