# Generated by Django 5.2.7 on 2025-11-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_interests_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_categories',
            field=models.JSONField(blank=True, default=list, help_text='User preferred category IDs as a list of integers'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_subcategories',
            field=models.JSONField(blank=True, default=list, help_text='User preferred subcategory IDs as a list of integers'),
        ),
    ]
