# Generated by Django 5.2.7 on 2025-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_preferred_categories_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_categories',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_subcategories',
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='User interests as a list of category names (strings)'),
        ),
    ]
