# Generated by Django 5.2.7 on 2025-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_preferred_categories_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advertising_enabled',
            field=models.BooleanField(default=True, help_text='Whether user wants to see personalized advertisements'),
        ),
    ]
