# Generated by Django 5.2.7 on 2025-11-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_advertising_enabled_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_promotional',
            field=models.BooleanField(default=True, help_text='Receive promotional emails'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text='Whether user wants to receive WhatsApp notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_order_updates',
            field=models.BooleanField(default=True, help_text='Receive WhatsApp notifications for order updates, shipments, payments and more'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_promotional',
            field=models.BooleanField(default=True, help_text='Receive WhatsApp notifications for personalised deals, recommendations, sales events, and more'),
        ),
    ]
