# Generated by Django 5.2.7 on 2025-11-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shipment_address',
            field=models.TextField(blank=True, help_text='Address for shipping orders', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipment_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipment_country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipment_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for geolocation', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipment_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for geolocation', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipment_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipment_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
