# Generated by Django 5.2.7 on 2025-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_vendor_shipment_address_vendor_shipment_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=100, help_text='Products with total stock below this value will be considered low stock'),
        ),
    ]
