# Generated by Django 5.2.7 on 2025-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_vendor_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Brand name to display on products', max_length=100, null=True),
        ),
    ]
