# Generated by Django 5.2.7 on 2025-11-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_vendor_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Bank account holder name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Branch name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for payments', max_length=100, null=True),
        ),
    ]
