# Generated by Django 5.2.7 on 2025-11-15 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_vendor_account_holder_name_vendor_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_url', models.URLField(help_text='Cloudinary URL of the uploaded image', max_length=500)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public ID for deletion', max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=200)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by_user', models.ForeignKey(blank=True, help_text='Admin user who uploaded this media', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by_vendor', models.ForeignKey(blank=True, help_text='Vendor/Seller who uploaded this media', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to='accounts.vendor')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
    ]
