# Generated by Django 5.2.7 on 2025-11-15 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('damaged', 'Damaged Item'), ('excessive_packaging', 'Excessive Packaging'), ('insufficient_packaging', 'Insufficient Packaging'), ('sustainability', 'Sustainability Concern'), ('other', 'Other')], default='general', max_length=50)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating from 1-5 (1=very poor, 5=excellent)', null=True)),
                ('was_helpful', models.BooleanField(blank=True, help_text='Whether the information was helpful (Yes/No)', null=True)),
                ('message', models.TextField(help_text='Detailed feedback message')),
                ('order_id', models.CharField(blank=True, help_text='Related order ID if applicable', max_length=100, null=True)),
                ('product_id', models.IntegerField(blank=True, help_text='Related product ID if applicable', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email for anonymous feedback', max_length=254, null=True)),
                ('name', models.CharField(blank=True, help_text='Name for anonymous feedback', max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_packaging_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the feedback (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Packaging Feedback',
                'verbose_name_plural': 'Packaging Feedback',
                'db_table': 'packaging_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
