# Generated by Django 5.2.7 on 2025-10-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminDashboardSetting',
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
    ]
