# Generated by Django 5.2.7 on 2025-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'View')], max_length=20),
        ),
    ]
