# Generated by Django 5.2.7 on 2025-11-05 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_alter_adminlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('version_number',)},
            },
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero_slider', 'Hero Slider'), ('hero_section_2', 'Hero Section 2'), ('hero_section_3', 'Hero Section 3'), ('categories', 'Categories'), ('furniture_sections', 'Furniture Sections'), ('offer_sections', 'Offer Sections'), ('feature_cards', 'Feature Cards'), ('banner_cards', 'Banner Cards'), ('info_section', 'Info Section')], max_length=50)),
                ('section_key', models.CharField(help_text='Unique key for this section instance', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.JSONField(default=dict, help_text='Section-specific content (images, text, links, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='admin_api.homepageversion')),
            ],
            options={
                'ordering': ['order', 'section_type'],
                'unique_together': {('section_type', 'section_key', 'version')},
            },
        ),
    ]
