# Generated by Django 5.2.7 on 2025-11-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_homepageversion_homepagesection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homepagesection',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='homepagesection',
            index=models.Index(fields=['version', 'section_type', 'section_key'], name='admin_api_h_version_da5775_idx'),
        ),
    ]
