# Generated by Django 5.2.7 on 2025-11-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_alter_homepagesection_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(help_text='Unique identifier for the section', max_length=100, unique=True)),
                ('section_name', models.CharField(help_text='Human-readable section name', max_length=200)),
                ('content', models.JSONField(default=dict, help_text='Section content as JSON')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is visible on the home page')),
                ('order', models.IntegerField(default=0, help_text='Display order on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Contents',
                'ordering': ['order', 'section_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='homepageversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='homepageversion',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='HomePageSection',
        ),
        migrations.DeleteModel(
            name='HomePageVersion',
        ),
    ]
