# Generated by Django 5.2.7 on 2025-11-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0009_faqpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Advertisement title (e.g., "Special Offer: 20% Off")', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description text')),
                ('image', models.URLField(help_text='Advertisement image URL', max_length=500)),
                ('button_text', models.CharField(default='Check Now', help_text='Button text (e.g., "Check Now", "Shop Now")', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Button link URL (product slug or external URL)', max_length=500)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount percentage to display (e.g., 20 for 20% Off)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this advertisement is active')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Advertisement start date/time', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Advertisement end date/time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
