# Generated by Django 5.2.7 on 2025-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_variant_orderitem_variant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee based on payment method', max_digits=10),
        ),
    ]
