# Generated by Django 5.2.7 on 2025-10-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_platform_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment gateway platform fee based on payment method', max_digits=10),
        ),
    ]
