# Generated by Django 5.2.7 on 2025-11-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_vendor'),
        ('orders', '0006_order_coupon_order_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who owns this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='accounts.vendor'),
        ),
    ]
