# Generated by Django 5.2.7 on 2025-11-15 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('defective', 'Defective'), ('incorrect', 'Incorrect Item'), ('not_as_described', 'Not as Described'), ('wrong_size', 'Wrong Size'), ('wrong_color', 'Wrong Color'), ('other', 'Other')], max_length=50)),
                ('reason_description', models.TextField(blank=True, help_text='Additional details about the return reason')),
                ('pickup_date', models.DateField(help_text='Preferred pickup date for the return')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('seller_approval', models.BooleanField(blank=True, help_text='Seller approval status: True=Approved, False=Rejected, None=Pending', null=True)),
                ('seller_notes', models.TextField(blank=True, help_text='Seller notes or comments')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Refund amount if approved', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
