# Generated by Django 5.2.7 on 2025-10-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # Create Material model
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        # Add new material_id field to Product
        migrations.AddField(
            model_name='product',
            name='material_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.material'),
        ),
        
        # Create materials from existing product materials
        migrations.RunPython(
            code=migrations.RunPython.noop,  # We'll handle this in a separate step
        ),
        
        # Remove old material field
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        
        # Rename material_new to material
        migrations.RenameField(
            model_name='product',
            old_name='material_new',
            new_name='material',
        ),
    ]
