# Generated by Django 5.2.7 on 2025-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
