# Generated by Django 5.2.7 on 2025-10-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='Care and maintenance instructions', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_offer',
            field=models.TextField(blank=True, help_text='Screen offer text to display on product page', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_guide',
            field=models.TextField(blank=True, help_text='User guide instructions', null=True),
        ),
    ]
