# Generated by Django 5.2.7 on 2025-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_care_instructions_product_screen_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='screen_offer',
            field=models.JSONField(blank=True, default=list, help_text='Array of screen offer texts to display on product page'),
        ),
    ]
