# Generated by Django 5.2.7 on 2025-10-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_screen_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=100, help_text='Threshold for low stock alert. Product is considered low stock if total variant stock is below this value.'),
        ),
    ]
