# Generated by Django 5.2.7 on 2025-11-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_low_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
    ]
