# Generated by Django 5.2.7 on 2025-11-03 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to='products.product')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to='products.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Browsing History',
                'verbose_name_plural': 'Browsing History',
                'db_table': 'browsing_history',
                'ordering': ['-last_viewed'],
            },
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
        migrations.AddIndex(
            model_name='browsinghistory',
            index=models.Index(fields=['user', '-last_viewed'], name='browsing_hi_user_id_941c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='browsinghistory',
            index=models.Index(fields=['user', 'category'], name='browsing_hi_user_id_3df6af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='browsinghistory',
            unique_together={('user', 'product')},
        ),
    ]
