# Generated by Django 5.2.7 on 2025-11-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['percentage'], 'verbose_name': 'Discount Filter Option', 'verbose_name_plural': 'Discount Filter Options'},
        ),
    ]
