# Generated by Django 5.2.7 on 2025-11-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_vendor'),
        ('products', '0013_alter_discount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor/Seller who owns this product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand name (can be different from vendor brand)', max_length=100),
        ),
    ]
