# Generated by Django 5.2.7 on 2025-11-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_vendor'),
        ('products', '0014_product_vendor_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who owns this coupon. If null, coupon applies to all products.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.vendor'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('code', 'vendor')},
        ),
    ]
