# Generated by Django 5.2.7 on 2025-11-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_coupon_vendor_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - unique product identifier', max_length=100, null=True, unique=True),
        ),
    ]
