# Generated by Django 5.2.7 on 2025-11-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('sixpine', 'Sixpine Products Only'), ('common', 'All Products (Common)'), ('seller', 'Seller Products (Platform Fee & Tax Only)')], default='common', help_text='Type of coupon: Sixpine products only, all products, or seller products (reduces only platform fee and tax)', max_length=20),
        ),
    ]
