# Generated by Django 5.2.7 on 2025-11-16 08:08

from django.db import migrations, models
import django.core.validators


def populate_variant_prices(apps, schema_editor):
    """Populate variant prices from product prices if variant price is null"""
    Product = apps.get_model('products', 'Product')
    ProductVariant = apps.get_model('products', 'ProductVariant')
    
    # Update variants with null prices to use product price (if product has price)
    for variant in ProductVariant.objects.filter(price__isnull=True):
        if variant.product and hasattr(variant.product, 'price') and variant.product.price:
            variant.price = variant.product.price
            variant.save()
        else:
            # Set default price of 0 if product doesn't have price
            variant.price = 0
            variant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_coupon_coupon_type'),
    ]

    operations = [
        # First, populate any null variant prices
        migrations.RunPython(populate_variant_prices, migrations.RunPython.noop),
        
        # Make variant price non-nullable
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Price is required for variants',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        
        # Remove price fields from Product model
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_on_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
    ]
