# Generated by Django 5.2.7 on 2025-11-16 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20251116_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage calculated from old_price and price', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('sixpine', 'Sixpine Products Only - Reduces product prices'), ('common', 'All Products (Common) - Reduces product prices'), ('seller', 'Platform Fee & Tax Only - Does NOT reduce seller product prices')], default='common', help_text='Type of coupon: Sixpine products only, all products, or seller products (reduces only platform fee and tax)', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
