# Generated by Django 5.2.7 on 2025-12-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productvariant_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Review must be approved by admin or vendor before appearing on product page'),
        ),
    ]
