# Generated by Django 5.2.7 on 2025-12-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productreview_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['color__name', 'size', 'pattern', 'quality']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_offer',
            field=models.JSONField(blank=True, default=list, help_text="Array of screen offer objects with 'title' and 'description' fields, or strings for backward compatibility"),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size', 'pattern', 'quality')},
        ),
    ]
