# Generated by Django 5.2.7 on 2025-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_add_quality_to_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.PositiveIntegerField(default=4, help_text='Estimated delivery time in days (e.g., 4 for 4 days)'),
        ),
    ]
