# Generated by Django 5.2.7 on 2025-12-02 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_add_estimated_delivery_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(help_text="Bullet point for 'About This Item' section")),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_items', to='products.product')),
            ],
            options={
                'verbose_name': 'About This Item',
                'verbose_name_plural': 'About This Item',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
