# Generated by Django 5.2.7 on 2025-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_add_product_about_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style_description',
            field=models.TextField(blank=True, help_text='Detailed style description for the Style section', null=True),
        ),
    ]
