# Generated by Django 5.2.7 on 2025-12-02 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_add_style_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.productvariant'),
        ),
    ]
