# Generated by Django 5.2.7 on 2025-12-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_move_specifications_to_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='what_in_box',
            field=models.TextField(blank=True, help_text='What is included in the box', null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='variant',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.productvariant'),
            preserve_default=False,
        ),
    ]
