# Generated by Django 5.2.7 on 2025-12-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_add_what_in_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='measurement_specs',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pairs for measurement details (e.g., {'Dimensions': '64 x 29 x 36 inch', 'Weight': '45 kg'})"),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='style_specs',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pairs for style details (e.g., {'Colour': 'Grey & Beige', 'Style': 'Modern', 'Shape': 'Rectangular'})"),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="Array of feature strings (e.g., ['Aesthetics', 'Comfort', 'Durable'])"),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='user_guide',
            field=models.TextField(blank=True, help_text='User guide instructions for this variant', null=True),
        ),
    ]

