# Generated by Django 5.2.7 on 2025-12-02 22:00

import json
from django.db import migrations, models


def convert_features_to_dict(apps, schema_editor):
    """Convert features from list to dict format using raw SQL"""
    db_alias = schema_editor.connection.alias
    from django.db import connections
    connection = connections[db_alias]
    
    with connection.cursor() as cursor:
        # Check if features column exists
        cursor.execute("PRAGMA table_info(products_productvariant)")
        columns = [col[1] for col in cursor.fetchall()]
        
        if 'features' not in columns:
            # Column doesn't exist, skip conversion
            return
        
        # Get all variants with features
        cursor.execute("SELECT id, features FROM products_productvariant WHERE features IS NOT NULL AND features != ''")
        rows = cursor.fetchall()
        
        for variant_id, features_json in rows:
            try:
                # Parse the JSON (it's stored as JSON in the database)
                if features_json:
                    features_data = json.loads(features_json) if isinstance(features_json, str) else features_json
                    
                    # Convert list to dict if it's a list
                    if isinstance(features_data, list):
                        features_dict = {f"Feature {i+1}": item for i, item in enumerate(features_data) if item}
                        # Update using raw SQL with proper escaping
                        features_json_str = json.dumps(features_dict).replace("'", "''")
                        cursor.execute(
                            f"UPDATE products_productvariant SET features = '{features_json_str}' WHERE id = {variant_id}"
                        )
                    # If it's already a dict, leave it as is
                    elif not isinstance(features_data, dict):
                        # If it's neither list nor dict, set to empty dict
                        cursor.execute(
                            f"UPDATE products_productvariant SET features = '{{}}' WHERE id = {variant_id}"
                        )
            except (json.JSONDecodeError, TypeError):
                # If parsing fails, set to empty dict
                cursor.execute(
                    f"UPDATE products_productvariant SET features = '{{}}' WHERE id = {variant_id}"
                )
        
        # Set NULL or empty features to empty dict
        cursor.execute("UPDATE products_productvariant SET features = '{}' WHERE features IS NULL OR features = ''")


def convert_user_guide_to_dict(apps, schema_editor):
    """Convert user_guide from text to dict format using raw SQL"""
    db_alias = schema_editor.connection.alias
    from django.db import connections
    connection = connections[db_alias]
    
    with connection.cursor() as cursor:
        # Check if user_guide column exists
        cursor.execute("PRAGMA table_info(products_productvariant)")
        columns = [col[1] for col in cursor.fetchall()]
        
        if 'user_guide' not in columns:
            # Column doesn't exist, skip conversion
            return
        
        # Get all variants with user_guide
        cursor.execute("SELECT id, user_guide FROM products_productvariant WHERE user_guide IS NOT NULL AND user_guide != ''")
        rows = cursor.fetchall()
        
        for variant_id, user_guide_text in rows:
            try:
                if user_guide_text:
                    # Try to parse as JSON first (in case it's already JSON)
                    try:
                        parsed = json.loads(user_guide_text) if isinstance(user_guide_text, str) else user_guide_text
                        if isinstance(parsed, dict):
                            # Already a dict, leave it as is
                            continue
                        else:
                            # Convert to dict
                            user_guide_dict = {"Instructions": str(user_guide_text)}
                    except (json.JSONDecodeError, TypeError):
                        # Not JSON, treat as plain text
                        user_guide_dict = {"Instructions": str(user_guide_text)}
                    
                    # Update using raw SQL with proper escaping
                    user_guide_json_str = json.dumps(user_guide_dict).replace("'", "''")
                    cursor.execute(
                        f"UPDATE products_productvariant SET user_guide = '{user_guide_json_str}' WHERE id = {variant_id}"
                    )
            except Exception:
                # If conversion fails, set to empty dict
                cursor.execute(
                    f"UPDATE products_productvariant SET user_guide = '{{}}' WHERE id = {variant_id}"
                )
        
        # Set NULL or empty user_guide to empty dict
        cursor.execute("UPDATE products_productvariant SET user_guide = '{}' WHERE user_guide IS NULL OR user_guide = ''")


def reverse_features_to_list(apps, schema_editor):
    """Reverse: Convert features from dict to list format"""
    ProductVariant = apps.get_model('products', 'ProductVariant')
    for variant in ProductVariant.objects.all():
        if variant.features and isinstance(variant.features, dict):
            # Convert dict to list
            variant.features = [f"{k}: {v}" for k, v in variant.features.items() if v]
            variant.save(update_fields=['features'])


def reverse_user_guide_to_text(apps, schema_editor):
    """Reverse: Convert user_guide from dict to text format"""
    ProductVariant = apps.get_model('products', 'ProductVariant')
    for variant in ProductVariant.objects.all():
        if variant.user_guide and isinstance(variant.user_guide, dict):
            # Convert dict to text (join all key-value pairs)
            variant.user_guide = "; ".join([f"{k}: {v}" for k, v in variant.user_guide.items() if v])
            variant.save(update_fields=['user_guide'])


def ensure_fields_exist(apps, schema_editor):
    """Ensure features and user_guide fields exist before altering them"""
    db_alias = schema_editor.connection.alias
    from django.db import connections
    connection = connections[db_alias]
    
    with connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(products_productvariant)")
        columns = [col[1] for col in cursor.fetchall()]
        
        # Add features field if it doesn't exist
        if 'features' not in columns:
            cursor.execute("ALTER TABLE products_productvariant ADD COLUMN features TEXT DEFAULT '[]'")
        
        # Add user_guide field if it doesn't exist
        if 'user_guide' not in columns:
            cursor.execute("ALTER TABLE products_productvariant ADD COLUMN user_guide TEXT DEFAULT ''")


def validate_all_json_fields(apps, schema_editor):
    """Validate and fix all JSON fields to ensure they're valid JSON before altering"""
    db_alias = schema_editor.connection.alias
    from django.db import connections
    connection = connections[db_alias]
    
    with connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(products_productvariant)")
        columns = [col[1] for col in cursor.fetchall()]
        
        json_fields = ['measurement_specs', 'style_specs', 'features', 'user_guide']
        
        for field_name in json_fields:
            if field_name not in columns:
                continue
            
            # Get ALL rows (including NULL and empty)
            cursor.execute(f"SELECT id, {field_name} FROM products_productvariant")
            rows = cursor.fetchall()
            
            for variant_id, field_value in rows:
                try:
                    # Handle NULL or empty values
                    if not field_value or field_value == '':
                        cursor.execute(
                            f"UPDATE products_productvariant SET {field_name} = '{{}}' WHERE id = {variant_id}"
                        )
                        continue
                    
                    # Try to parse as JSON
                    parsed = json.loads(field_value) if isinstance(field_value, str) else field_value
                    
                    # Ensure it's a dict (for measurement_specs, style_specs, features, user_guide)
                    if not isinstance(parsed, dict):
                        # Convert to dict if it's not already
                        if isinstance(parsed, list):
                            parsed = {f"Item {i+1}": item for i, item in enumerate(parsed) if item}
                        else:
                            parsed = {"Value": str(parsed)}
                    
                    # Update with valid JSON
                    field_json_str = json.dumps(parsed).replace("'", "''")
                    cursor.execute(
                        f"UPDATE products_productvariant SET {field_name} = '{field_json_str}' WHERE id = {variant_id}"
                    )
                except (json.JSONDecodeError, TypeError, ValueError) as e:
                    # If invalid JSON, set to empty dict
                    cursor.execute(
                        f"UPDATE products_productvariant SET {field_name} = '{{}}' WHERE id = {variant_id}"
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_add_variant_specific_info'),
    ]

    operations = [
        # Ensure fields exist first
        migrations.RunPython(ensure_fields_exist, migrations.RunPython.noop),
        # Validate and fix all JSON fields first (including measurement_specs and style_specs)
        migrations.RunPython(validate_all_json_fields, migrations.RunPython.noop),
        # Convert data using raw SQL to avoid validation issues
        migrations.RunPython(convert_features_to_dict, reverse_features_to_list),
        migrations.RunPython(convert_user_guide_to_dict, reverse_user_guide_to_text),
        # Validate again after conversion to ensure everything is valid
        migrations.RunPython(validate_all_json_fields, migrations.RunPython.noop),
        # Then alter fields
        migrations.AlterField(
            model_name='productvariant',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pairs for features (e.g., {'Weight Capacity Maximum': '450 Kilograms', 'Seating Capacity': '3.0'})"),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='user_guide',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pairs for user guide (e.g., {'Assembly': 'Required', 'Care Instructions': 'Wipe with dry cloth'})"),
        ),
    ]
