# Generated by Django 5.2.7 on 2025-12-03 14:16

from django.db import migrations, models


def add_missing_columns(apps, schema_editor):
    """Add missing variant-specific columns if they don't exist"""
    db_alias = schema_editor.connection.alias
    from django.db import connections
    connection = connections[db_alias]
    
    with connection.cursor() as cursor:
        # Check existing columns
        cursor.execute("PRAGMA table_info(products_productvariant)")
        columns = [col[1] for col in cursor.fetchall()]
        
        # Add measurement_specs if missing
        if 'measurement_specs' not in columns:
            cursor.execute(
                "ALTER TABLE products_productvariant ADD COLUMN measurement_specs TEXT DEFAULT '{}'"
            )
        
        # Add style_specs if missing
        if 'style_specs' not in columns:
            cursor.execute(
                "ALTER TABLE products_productvariant ADD COLUMN style_specs TEXT DEFAULT '{}'"
            )
        
        # Add features if missing (as JSONField with dict default)
        if 'features' not in columns:
            cursor.execute(
                "ALTER TABLE products_productvariant ADD COLUMN features TEXT DEFAULT '{}'"
            )
        
        # Add user_guide if missing (as JSONField with dict default)
        if 'user_guide' not in columns:
            cursor.execute(
                "ALTER TABLE products_productvariant ADD COLUMN user_guide TEXT DEFAULT '{}'"
            )
        
        # Update all NULL or empty values to empty dict JSON
        cursor.execute("UPDATE products_productvariant SET measurement_specs = '{}' WHERE measurement_specs IS NULL OR measurement_specs = ''")
        cursor.execute("UPDATE products_productvariant SET style_specs = '{}' WHERE style_specs IS NULL OR style_specs = ''")
        cursor.execute("UPDATE products_productvariant SET features = '{}' WHERE features IS NULL OR features = ''")
        cursor.execute("UPDATE products_productvariant SET user_guide = '{}' WHERE user_guide IS NULL OR user_guide = ''")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_change_features_user_guide_to_keyvalue'),
    ]

    operations = [
        migrations.RunPython(add_missing_columns, migrations.RunPython.noop),
    ]
