# Generated by Django 5.2.7 on 2025-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_add_missing_variant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Multiple subcategories this product belongs to (e.g., 1 Seater, 2 Seater, 3 Seater)', related_name='product_set', to='products.subcategory'),
        ),
    ]
