# Generated by Django 5.2.7 on 2025-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_add_multiple_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Subcategories this variant belongs to (e.g., 1 Seater, 2 Seater)', related_name='variants', to='products.subcategory'),
        ),
    ]
