# Generated by Django 5.2.7 on 2025-12-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_add_variant_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='products.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
