# Generated by Django 5.2.7 on 2025-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_add_product_item_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='item_details',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pairs for item details (e.g., {'Assembly': 'Required', 'Warranty': '1 Year', 'Weight': '45 kg'})"),
        ),
        migrations.DeleteModel(
            name='ProductItemDetail',
        ),
    ]
