# Generated by Django 5.2.7 on 2025-12-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_add_variant_item_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='features',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='item_details',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='measurement_specs',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='style_specs',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='user_guide',
        ),
        migrations.CreateModel(
            name='VariantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Feature',
                'verbose_name_plural': 'Variant Features',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariantItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Item Detail',
                'verbose_name_plural': 'Variant Item Details',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariantMeasurementSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_specs', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Measurement Specification',
                'verbose_name_plural': 'Variant Measurement Specifications',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariantStyleSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_specs', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Style Specification',
                'verbose_name_plural': 'Variant Style Specifications',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariantUserGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_guide', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Variant User Guide',
                'verbose_name_plural': 'Variant User Guides',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
