# Generated by Django 5.2.7 on 2025-12-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_productvariant_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of attachment objects with url, type, and name'),
        ),
    ]
