# Generated by Django 5.2.7 on 2025-12-26 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_productreview_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('specifications', 'Specifications'), ('measurement_specs', 'Measurement Specifications'), ('style_specs', 'Style Specifications'), ('features', 'Features'), ('user_guide', 'User Guide'), ('item_details', 'Item Details')], max_length=50)),
                ('field_name', models.CharField(help_text='Default field name (e.g., "Brand", "Weight", "Bed Type")', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_templates', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Specification Template',
                'verbose_name_plural': 'Category Specification Templates',
                'ordering': ['category', 'section', 'sort_order', 'field_name'],
                'unique_together': {('category', 'section', 'field_name')},
            },
        ),
    ]
