# Generated by Django 5.2.7 on 2026-01-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_add_variant_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit for this variant', max_length=100, null=True),
        ),
    ]
