# Generated by Django 5.2.7 on 2026-01-16 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_add_variant_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantfeature',
            options={'ordering': ['sort_order'], 'verbose_name': 'Variant Feature', 'verbose_name_plural': 'Variant Features'},
        ),
        migrations.AlterModelOptions(
            name='variantitemdetail',
            options={'ordering': ['sort_order'], 'verbose_name': 'Variant Item Detail', 'verbose_name_plural': 'Variant Item Details'},
        ),
        migrations.AlterModelOptions(
            name='variantmeasurementspec',
            options={'ordering': ['sort_order'], 'verbose_name': 'Variant Measurement Specification', 'verbose_name_plural': 'Variant Measurement Specifications'},
        ),
        migrations.AlterModelOptions(
            name='variantstylespec',
            options={'ordering': ['sort_order'], 'verbose_name': 'Variant Style Specification', 'verbose_name_plural': 'Variant Style Specifications'},
        ),
        migrations.AlterModelOptions(
            name='variantuserguide',
            options={'ordering': ['sort_order'], 'verbose_name': 'Variant User Guide', 'verbose_name_plural': 'Variant User Guides'},
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
