# Generated by Django 5.2.7 on 2026-01-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_variantfeature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='reviewer_name',
            field=models.CharField(blank=True, help_text='Custom reviewer name for admin-created reviews', max_length=200),
        ),
    ]
