# Generated by Django 5.2.7 on 2026-01-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_navbar_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_main_image',
            field=models.URLField(blank=True, help_text='Main parent image URL - displayed in product tiles when variants reference parent', max_length=500, null=True),
        ),
    ]
